### ISSUE TITLE
Build the extractor

### ISSUE THREAD

**Issue by pp23** [iljabauer/quamo-wiki#30]
At first, we need the following data from the extractor:
- mapping of sentences to their corresponding test support functions
- mapping of sentences to their corresponding testcases/scenarios

**Comment by iljabauer** [comment]
So I will need until Tuesday to finish the extractor. The information you mention can not be provided by the extractor, this will be provided by the runner. This will not get done until Tuesday because I will require some classes which are internal in the natspec libraries. So I will have to extend NatSpec and build a factory for this. And this will need a merge into the trunk.

Should I provide you a example xml for this information?

**Comment by pp23** [comment]
> Should I provide you a example xml for this information?

If it will not generate too much work you can do it. But without these mapping data we just cannot calculate the related metrics. Hence I think we can wait until tuesday. It depends only a few metrics.
